### PR TITLE
Add `core-js` implementation

### PR DESCRIPTION
**Pull request by zloirock**

### CODE REVIEW

**Comment by ljharb** [comment]
I don't think it's appropriate to link to implementations of a proposal prior to stage 3.

**Comment by zloirock** [comment]
@ljharb do you understand how funny your comment looks when **your** polyfills are added even on the early stages? For example, https://github.com/tc39/proposal-symbol-predicates#polyfill-implementations

**Comment by ljharb** [comment]
Those aren’t polyfills - they’re predicates, that predate and inspire the entire proposal.

**Comment by zloirock** [comment]
Predicates. Proposed as polyfills in the polyfills section.

**Comment by ljharb** [comment]
Yes, because the implementation of the predicates matches the spec, not because they self-install on the global.

**Comment by zloirock** [comment]
Awesome. Like `core-js` implementation that matches the spec and can be used without self-install on the global. No difference.

Do you even read what you write? "Polyfills should not be added, however, my polyfills are not polyfills, but since they match the spec, let's add them and call them polyfills."

**Comment by ljharb** [comment]
Mine are not polyfills - they *predate* the spec. They *happen* to match the spec.

This entire argument isn't productive, so i'm going to hide it all as off topic.

**Comment by zloirock** [comment]
And because of this, **they are marked as polyfills**, but not as a "prior art"? 😂 It's not productive to hide your failures instead of fixing them.

**Comment by ljharb** [comment]
You're right, that readme is inaccurate - the original champion created it. I'll fix it. It's still all off topic for *this repo and PR*, so please don't continue this discussion.

**Pull request closed without merging**
